CREATE TABLE "Course" (
   "id" UUID PRIMARY KEY,
   "status" VARCHAR NOT NULL,
   "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
   "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
   "createdBy" VARCHAR NOT NULL,
   "updatedBy" VARCHAR NOT NULL,
   "name" VARCHAR NOT NULL,
   "description" VARCHAR NOT NULL
);
